### ISSUE TITLE
PF1: Pre v9 created actors have blank conditions added

### ISSUE THREAD

**Issue by Koalahund** [Drental/fvtt-tokenactionhud#135]
PF1 v0.80.3
Foundry Build 9.241
Token Action HUD v 2.0.10

Problem: Older actors (created pre v9) have blank conditions added, also the "Blind" condition is in the wrong spot
![1](https://user-images.githubusercontent.com/85458282/148575425-0a365d36-6c98-4b2f-8b10-eeb4ead80d87.png)
Working on new actors:
![2](https://user-images.githubusercontent.com/85458282/148575463-7f90ef35-d8d0-46b3-8a18-dbe7e20ea552.png)

**Comment by Drental** [comment]
as you correctly Identify this is caused by no longer used but leftover data on the actor itself.

I feel that pruning the actor data goes beyond the scope of this module (and my abilities)

I am accepting PRs for this, but culturally I rather go with "rebuild your character from time to time" - if that is not feasible in pf1 I might reconsider.
