### ISSUE TITLE
List is too long to display all items

### ISSUE THREAD

**Issue by Farmeroz** [Drental/fvtt-tokenactionhud#176]
Thank you for putting in support for GURPS!

GURPS often has *long* lists under categories (such as spells, or skills, and so on).  Basically, it's very easy to find that the list is so long it goes off the bottom of the screen and I couldn't find a setting to make it 'wrap' into extra columns.  Is there a way to do this?  Otherwise many of the items are not accessible.

Thanks!

**Comment by crnormand** [comment]
The issue is how I generated the action lists.   Each Skill/Spell is a Subcategory, so that is displays vertically, and then any OtFs that are detected in the Skill/Spell name (and notes), will be displayed to the right (p.s. you will not get this display yet, until PR https://github.com/Drental/fvtt-tokenactionhud/pull/177 is accepted).

![image](https://user-images.githubusercontent.com/8931036/157350342-dfe3ce92-f215-467b-b60e-27ab708e0831.png)

I could just load up the list of actions without using subcategories, which allows Token Action HUD to wrap the buttons, ex: Maneuvers
![image](https://user-images.githubusercontent.com/8931036/157350466-1a6c7233-6f28-488b-acd4-94801b510777.png)

But then it would look completely disorganized if a Skill/Spell has OtFs in their names/notes.  So I don't have a good solution for this.

Can you attach a .GCS file (zipped) so I can see how bad it is?

**Comment by crnormand** [comment]
Ok, I think I have a good solution.   I've added a new module setting:
![image](https://user-images.githubusercontent.com/8931036/157362261-7a107bbe-b30e-4a18-b818-c03020ad3852.png)

Skill/Spells lists greater than that number will split it multiple columns:
![image](https://user-images.githubusercontent.com/8931036/157362380-a87e1629-1fd7-48ca-8162-43c26cf56913.png)
![image](https://user-images.githubusercontent.com/8931036/157362444-abdbb566-544c-4d4c-94fe-8f9b206fad17.png)
![image](https://user-images.githubusercontent.com/8931036/157362673-131fb17d-3748-4fe1-8f3a-53a4db5139ef.png)

Good enough?

**Comment by Farmeroz** [comment]
Thanks, Chris - I think that will work really well.  Sorry for the late reply - time zone differences :-).  I was actually at work and saw your updates but couldn't respond.

Just for interest, I have attached a ZIP of a GCA export to FVTT file that has plenty of skills and spells (I use GCA not GCS).

[Alisha Dhovi.zip](https://github.com/Drental/fvtt-tokenactionhud/files/8211959/Alisha.Dhovi.zip)

**Comment by crnormand** [comment]
But you are going to switch to GCS soon, right?  ;-)  (j/k)

**Comment by crnormand** [comment]
Wow, that character really does have a lot of spells.

![image](https://user-images.githubusercontent.com/8931036/157472685-fd91e0cf-ec30-4122-9a96-56dd52fafa6e.png)
![image](https://user-images.githubusercontent.com/8931036/157472811-a83bf681-0de7-4f7e-84eb-db9b6d46f618.png)

**Comment by Drental** [comment]
why is that list single column?
do I need to check your Code after all sir?

**Comment by Farmeroz** [comment]
> Wow, that character really does have a lot of spells.

And it will grow :-)  And if you ever see a Spec Ops character, the skill list is never ending!

It looks really good in your example and I think that will work very well, thanks.  GCS?  I did try it and it looks great, I'm just too used to GCA and the new GCA5 is awesome.  Appreciate that you support both!

**Comment by Farmeroz** [comment]
This is working well with the latest update just released which includes the GURPS updates.  Thanks!
