### ISSUE TITLE
[Request] Compatibility with the action tabs module for foundry

### ISSUE THREAD

**Issue by Orionox** [Drental/fvtt-tokenactionhud#210]
There's a really cool foundry module that adds a tab that sorts stuff byy what kind of action it takes to use. It would be awesome if the token HUD ahd a section for "actions" which mirrored the information found ont he actions tab.

**Comment by Larkinabout** [comment]
Grouping actions by activation type as well as item type is supported in the new [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e). Note that it won't reflect the tab created by the 'Character Actions List' module as the feature is build in rather than looking at another module. However, you can add/remove and sort actions directly on the HUD.
