### ISSUE TITLE
Pathfinder 1 Arcanist Prepared Spells

### ISSUE THREAD

**Issue by andr108** [Drental/fvtt-tokenactionhud#214]
HUD shows _all_ spells known for Arcanist characters, instead of just prepared spells, as is the case with e.g. Wizards.
Of course, this class prepares spells in a different way than the other prepared spellcasters.

**Comment by Larkinabout** [comment]
Looking into this one in release 3.0.4, there is some strange behaviour where a spell will remain on the HUD until the spell's item window is closed. Unticking **Prepared** alone does not remove the spell. This seems to be because until the window is closed the preparation.preparedAmount on the spell is greater than zero (where there are prepared slots remaining).

This could be resolved by skipping the check for preparedAmount where the spellbook is spontaneous, but further investigation is needed first.

**Comment by Larkinabout** [comment]
Fixed in release 3.0.5.
