### ISSUE TITLE
HUD displaying strangely 

### ISSUE THREAD

**Issue by mawp42** [Drental/fvtt-tokenactionhud#222]
After the recent update the HUD displays along the left side of the screen, and expands to fill the screen. I've tried loading with no other modules and this occurs in the client and browser. I'm on v9 of Foundry using the latest version of 5e running on Windows 11. Any ideas? 
<img width="1918" alt="Screenshot_2022-06-07_181138" src="https://user-images.githubusercontent.com/101284532/172590590-cc419224-41b4-41ba-82fa-2c3938511de9.png">

**Comment by Drental** [comment]
this is caused by the css not loading correctly.
try reloading, then uninstalling the module and installing it again.
also try to delete the module in the modules folder while your instance is shut down if a simple reinstall does not work to be sure that all files are gone and a new download can be successful
