### ISSUE TITLE
v10

### ISSUE THREAD

**Issue by Theopholis** [Drental/fvtt-tokenactionhud#251]
Having problems getting weapons to work in the HUD with Midi-QLL. When I setup the automation in Midi-QLL, the weapons and spells won't work, but the saves and checks will. When I remove Midi-QLL automation, HUD works.

**Comment by bearsy1** [comment]
+1
You are probably already on it for the update, but I too am having this issue.

**Comment by Drental** [comment]
I do in fact no longer have the time to maintain this module.

prior to just now I didn't even have a loading release for v10.

please get people to help out, because my update timeline might well be never :(

**Comment by Larkinabout** [comment]
If this is for D&D 5e, this should be fixed in 3.0.1 as item#roll is replaced with item#use. I've tested as working with and without midi-qol enabled.

One thing I noticed is that if you have targetting required in midi-qol, item uses don't seem to trigger a warning to target a token, so you'll just need to make sure you're targetting when using items from the HUD's inventory. Spells do trigger a targetting warning.
