### ISSUE TITLE
Add Support: Forbidden Lands

### ISSUE THREAD

**Issue by Drental** [Drental/fvtt-tokenactionhud#26]

**Comment by apoapostolov** [comment]
@Drental since there is a plan to break into Core + system configurations, maybe allow system developers to incorporate the system configuration module in their systems. Also, for new systems, maybe approach the system community with a call for developer of the system configuration once the Core migration is complete?

Just throwing few cents in.

**Comment by Drental** [comment]
I don't try to stretch myself thin over this, don't worry. I just keep these issues because I need to remember who asked.

**Comment by Drental** [comment]
Halfway done, but.
at the current time I have no intention to add support for additional systems. Closing to get a better overview of the state of the module.
