### ISSUE TITLE
Pathfinder 2e 

### ISSUE THREAD

**Issue by bb46003** [Drental/fvtt-tokenactionhud#273]
Hi I have problem after migration to V10 build 285 with system version 4.0.5, all NPC token desn't have their action in HUD unless i link token with character sheet or I drag new token to scene, it is possible to fix it or I need to put all NPC again to all scenes ?

**Comment by Larkinabout** [comment]
It sounds like the migration didn't quite sort everything and the tokens on the canvas are missing something that the HUD now needs to function. Because it sounds like the HUD works as expected after linking a token to a character sheet or dropping a new token to the canvas, it's possible the existing tokens just need replacing to update them. If that's a big task, it might be worth raising the issue with the Pathfinder 2 system developers or Discord group to see if it's a known issue with a workaround.

**Comment by Drental** [comment]
check that the items on the tokens have actually more than their name.

there is a bug that breaks npc token items quite thoroughly when migrating to v10 under certain conditions.

**Comment by stwlam** [comment]
This was a bug in FVTT 10.285 and is now resolved in 10.286.

**Comment by Larkinabout** [comment]
Thanks for the update, @stwlam.
