### ISSUE TITLE
Ability to modify basic categories like the custom categories

### ISSUE THREAD

**Issue by Drental** [Drental/fvtt-tokenactionhud#28]
In some cases it would be nice to remove a subcategory from core categories or blacklist items if they're covered by macros elsewhere.

aka: make the base queries more generic(?)

**Comment by apoapostolov** [comment]
If the system data is a pair file of a functions JS with a JSON configuration file with name, metadata and query for each category, this would allow power users to do anything, from renaming categories in the config file to editing the queries themselves, and adding new categories with ease.

**Comment by happy-cujo** [comment]
Just adding my 2 cents.

HUD is lacking some basic functionalities that allow us to customize (main) categories, like removing/hiding or reordering them.

A structure of the HUD and it's categories (including subcategories) should be editable from configuration page. In the scope of what could be configured I have a list:
- The main category is only a placeholder for subcategories. 
- A subcategory can define what type of data it stores (items/attributes/skills/features/conditions/effects) and then it should allow further filtering based on defined type. Example: "items" subcategory allows you to include "weapons", "features", "spells", and so on. Each of those option you can check/uncheck. For each option you can set up additional filtering (something that renders a form similar to the one from item details tab of given item type). In this form you can define that attributes given item should have in order to show up.
- All of the subcategories should allow whitelisting/blacklisting it's items by name. 
- Each of the subcategories should have toggle to hide/show for players or/and permission check (example: only trusted players can see and use category with effects/conditions)
- Allowing more options in filtering can result in heavy operations, so some kind of more advanced cache needs to be added (like listening on add/remove/update events for given document to add or remove it from token/actor cache). 
- It could be beneficial to have such configurations stored per token/actor type (or linked/unlinked token). A NPC token doesn't need to show the same categories as a player's token does. For NPC single category "Actions" that contain "Items", "Spells", "Features" subcategories is more that enough. Players have wider range of options to chose from so splitting them on root level makes more sense.
- Allow categories/subcategories reordering (could be a part of first element of this list).
- Player itself can hide/show defined categories, but there is no need to give him access to add new or modify existing.

**Comment by Larkinabout** [comment]
Resolved for D&D 5e with [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e). Development of this nature will now continue with [Token Action HUD Core](https://github.com/Larkinabout/fvtt-token-action-hud-core).
