### ISSUE TITLE
Change HUD propagation direction

### ISSUE THREAD

**Issue by Drental** [Drental/fvtt-tokenactionhud#29]
expand the HUD to the left or right from the anchor and/or show the groups above the HUD instead of under it

**Comment by Drental** [comment]
worked already

**Comment by happy-cujo** [comment]
I would expand this one a little bit more, or I can delegate new issue if necessary.

The HUD is always horizontal, but in some cases (wide screens) it makes more sense to put in game windows/widgets on the sides, but then HUD doesn't looks nice/fits into it's place. My proposition is to allow changing the orientation of HUD on user level. Potential configurations that can be achieved would be:
- horizontal, categories below (current default, "Dropdown categories: Yes")
- horizontal, categories above ("Dropdown categories: No")
- vertical, categories on the left (new)
- vertical, categories on the right (new)
- 
"below/above" and "left/right" could be the same option in configuration, like "Expand on opposite side: Yes/No".
New configuration option should be introduced, like "Orientation: Horizontal/Vertical".

Also because vertical orientation would create width inconsistency there could be an option to set fixed width or match widest element.

Sample visualization:
![directions_mock](https://user-images.githubusercontent.com/15898113/126016607-16626d8f-1bd6-41c4-bdfe-40c602e622d5.jpg)

**Comment by Drental** [comment]
I can see this. I don't know when or if I can do this, but this is reasonably issue worthy.

**Comment by Larkinabout** [comment]
Replaced by Larkinabout/fvtt-token-action-hud-core#12.
