### ISSUE TITLE
Blank boxes in drop down

### ISSUE THREAD

**Issue by ckdragons** [Drental/fvtt-tokenactionhud#389]
What is the reason for the blank boxes found under Conditions drop down?

![image](https://user-images.githubusercontent.com/84493092/222883709-387cdbdb-e1a7-4a79-a6a8-e45ab172b067.png)

**Comment by Larkinabout** [comment]
What system is this? It's likely that the source of the conditions has some elements without labels.

**Comment by Larkinabout** [comment]
Hi @ckdragons, support for Pathfinder 1e has now moved to the dedicated [Token Action HUD Pathfinder 1e](https://foundryvtt.com/packages/token-action-hud-pf1) module. Check out that module and if the issue is still happening, raise the issue here: [Token Action HUD Pathfinder 1e Issues](https://github.com/dmrickey/token-action-hud-pf1/issues).

**Comment by ckdragons** [comment]
Thank you. I will need to replace _Token Action HUD_ with _Token Action HUD Core_ + _Token Action Pathfinder 1e_?
