### ISSUE TITLE
add hotkeys and A11y support

### ISSUE THREAD

**Issue by Drental** [Drental/fvtt-tokenactionhud#43]
The token action hud is a  full sheet accessing module, it would be best if it could add an interface for blind people to get better use out of foundry.

**Comment by Puddinglord** [comment]
I am working on an accessibility module for a visually impaired person that I play PF2e Society with and talked about helping make this module easier for them to use since chapter sheets mean nothing to them. They currently either have others roll for them or just more macros than necessary.

They and I fully support this feature, and if you'd like help with it and UX help/direction, I'd be more than happy to assist.

**Comment by Drental** [comment]
I added this more as a stretch goal with no expectations of finishing it soon or specific plans.

I'll gladly take any opinions on UX since I personally don't have the experience of using screenreaders or making clean workflows.

**Comment by Larkinabout** [comment]
Replaced by Larkinabout/fvtt-token-action-hud-core#14.
