### ISSUE TITLE
Don't work anymore with Version 11.315

### ISSUE THREAD

**Issue by Stain27** [Drental/fvtt-tokenactionhud#441]
I'm not an expert in VTT, but since I upgraded the Foundry Virtual Tabletop at the last version released the 7 november the HUD doesn't appear anymore.
Thanks anyone for the help
![VTT the forge](https://github.com/Drental/fvtt-tokenactionhud/assets/163293665/71e059af-3c12-46a7-9804-2205b3e6542e)

**Comment by SolalDR** [comment]
Hello, and thank you for this magnificent module!

I have the same problem. I believe the problem comes from the `_getAbilityList` function (in my case in the `/scripts/actions/sw5e/sw5e-actions.js` file). 

I've got the following error in my console. 

<img width="555" alt="Capture d’écran 2024-04-09 à 00 39 28" src="https://github.com/Drental/fvtt-tokenactionhud/assets/14965864/3b09f146-e549-4404-ab21-2e1f896a5d93">

It seems `name` variable is undefined here

```javascript
  /** @private */
  _getAbilityList(tokenId, abilities, categoryId, categoryName, macroType) {
    let result = this.initializeEmptyCategory(categoryId);
    result.name = categoryName;

    let abbr = settings.get("abbreviateSkills");

    let actions = Object.entries(game.sw5e.config.abilities).map((e) => {
      if (abilities[e[0]].value === 0) return;

      let name = abbr ? e[0] : e[1];
      name = name.charAt(0).toUpperCase() + name.slice(1);
      let encodedValue = [macroType, tokenId, e[0]].join(this.delimiter);
      let icon;
      if (categoryId === "checks") icon = "";
      else icon = this._getProficiencyIcon(abilities[e[0]].proficient);

      return { name: name, id: e[0], encodedValue: encodedValue, icon: icon };
    });
```

**Comment by SolalDR** [comment]
I just fixed the problem locally by modifying this line `let name = abbr ? e[0]: e[1].label;`
I don't think I know the software enough to create a PR on this issue but I think it's a good base :)
